/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.jdbc;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.dto.*;
import com.app.dal.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class InvoiceLineDaoImpl extends AbstractDAO implements InvoiceLineDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, invoice_id, item_id, price, quantity, total_price, type, code FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id, invoice_id, item_id, price, quantity, total_price, type, code ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, invoice_id = ?, item_id = ?, price = ?, quantity = ?, total_price = ?, type = ?, code = ? WHERE id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column invoice_id
	 */
	protected static final int COLUMN_INVOICE_ID = 2;

	/** 
	 * Index of column item_id
	 */
	protected static final int COLUMN_ITEM_ID = 3;

	/** 
	 * Index of column price
	 */
	protected static final int COLUMN_PRICE = 4;

	/** 
	 * Index of column quantity
	 */
	protected static final int COLUMN_QUANTITY = 5;

	/** 
	 * Index of column total_price
	 */
	protected static final int COLUMN_TOTAL_PRICE = 6;

	/** 
	 * Index of column type
	 */
	protected static final int COLUMN_TYPE = 7;

	/** 
	 * Index of column code
	 */
	protected static final int COLUMN_CODE = 8;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 8;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the invoice_line table.
	 */
	public InvoiceLinePk insert(InvoiceLine dto) throws InvoiceLineDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getId() );
			if (dto.isInvoiceIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getInvoiceId() );
			}
		
			if (dto.isItemIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getItemId() );
			}
		
			if (dto.isPriceNull()) {
				stmt.setNull( index++, java.sql.Types.DOUBLE );
			} else {
				stmt.setDouble( index++, dto.getPrice() );
			}
		
			if (dto.isQuantityNull()) {
				stmt.setNull( index++, java.sql.Types.DOUBLE );
			} else {
				stmt.setDouble( index++, dto.getQuantity() );
			}
		
			if (dto.isTotalPriceNull()) {
				stmt.setNull( index++, java.sql.Types.DOUBLE );
			} else {
				stmt.setDouble( index++, dto.getTotalPrice() );
			}
		
			stmt.setString( index++, dto.getType() );
			stmt.setString( index++, dto.getCode() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setId( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InvoiceLineDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the invoice_line table.
	 */
	public void update(InvoiceLinePk pk, InvoiceLine dto) throws InvoiceLineDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getId() );
			if (dto.isInvoiceIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getInvoiceId() );
			}
		
			if (dto.isItemIdNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getItemId() );
			}
		
			if (dto.isPriceNull()) {
				stmt.setNull( index++, java.sql.Types.DOUBLE );
			} else {
				stmt.setDouble( index++, dto.getPrice() );
			}
		
			if (dto.isQuantityNull()) {
				stmt.setNull( index++, java.sql.Types.DOUBLE );
			} else {
				stmt.setDouble( index++, dto.getQuantity() );
			}
		
			if (dto.isTotalPriceNull()) {
				stmt.setNull( index++, java.sql.Types.DOUBLE );
			} else {
				stmt.setDouble( index++, dto.getTotalPrice() );
			}
		
			stmt.setString( index++, dto.getType() );
			stmt.setString( index++, dto.getCode() );
			stmt.setInt( 9, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InvoiceLineDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the invoice_line table.
	 */
	public void delete(InvoiceLinePk pk) throws InvoiceLineDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InvoiceLineDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the invoice_line table that matches the specified primary-key value.
	 */
	public InvoiceLine findByPrimaryKey(InvoiceLinePk pk) throws InvoiceLineDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'id = :id'.
	 */
	public InvoiceLine findByPrimaryKey(int id) throws InvoiceLineDaoException
	{
		InvoiceLine ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria ''.
	 */
	public InvoiceLine[] findAll() throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id", null );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'id = :id'.
	 */
	public InvoiceLine[] findWhereIdEquals(int id) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'invoice_id = :invoiceId'.
	 */
	public InvoiceLine[] findWhereInvoiceIdEquals(int invoiceId) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE invoice_id = ? ORDER BY invoice_id", new Object[] {  new Integer(invoiceId) } );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'item_id = :itemId'.
	 */
	public InvoiceLine[] findWhereItemIdEquals(int itemId) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE item_id = ? ORDER BY item_id", new Object[] {  new Integer(itemId) } );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'price = :price'.
	 */
	public InvoiceLine[] findWherePriceEquals(double price) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE price = ? ORDER BY price", new Object[] {  new Double(price) } );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'quantity = :quantity'.
	 */
	public InvoiceLine[] findWhereQuantityEquals(double quantity) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE quantity = ? ORDER BY quantity", new Object[] {  new Double(quantity) } );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'total_price = :totalPrice'.
	 */
	public InvoiceLine[] findWhereTotalPriceEquals(double totalPrice) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE total_price = ? ORDER BY total_price", new Object[] {  new Double(totalPrice) } );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'type = :type'.
	 */
	public InvoiceLine[] findWhereTypeEquals(String type) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE type = ? ORDER BY type", new Object[] { type } );
	}

	/** 
	 * Returns all rows from the invoice_line table that match the criteria 'code = :code'.
	 */
	public InvoiceLine[] findWhereCodeEquals(String code) throws InvoiceLineDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE code = ? ORDER BY code", new Object[] { code } );
	}

	/**
	 * Method 'InvoiceLineDaoImpl'
	 * 
	 */
	public InvoiceLineDaoImpl()
	{
	}

	/**
	 * Method 'InvoiceLineDaoImpl'
	 * 
	 * @param userConn
	 */
	public InvoiceLineDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "fruits.invoice_line";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected InvoiceLine fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			InvoiceLine dto = new InvoiceLine();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected InvoiceLine[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			InvoiceLine dto = new InvoiceLine();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		InvoiceLine ret[] = new InvoiceLine[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(InvoiceLine dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setInvoiceId( rs.getInt( COLUMN_INVOICE_ID ) );
		if (rs.wasNull()) {
			dto.setInvoiceIdNull( true );
		}
		
		dto.setItemId( rs.getInt( COLUMN_ITEM_ID ) );
		if (rs.wasNull()) {
			dto.setItemIdNull( true );
		}
		
		dto.setPrice( rs.getDouble( COLUMN_PRICE ) );
		if (rs.wasNull()) {
			dto.setPriceNull( true );
		}
		
		dto.setQuantity( rs.getDouble( COLUMN_QUANTITY ) );
		if (rs.wasNull()) {
			dto.setQuantityNull( true );
		}
		
		dto.setTotalPrice( rs.getDouble( COLUMN_TOTAL_PRICE ) );
		if (rs.wasNull()) {
			dto.setTotalPriceNull( true );
		}
		
		dto.setType( rs.getString( COLUMN_TYPE ) );
		dto.setCode( rs.getString( COLUMN_CODE ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(InvoiceLine dto)
	{
	}

	/** 
	 * Returns all rows from the invoice_line table that match the specified arbitrary SQL statement
	 */
	public InvoiceLine[] findByDynamicSelect(String sql, Object[] sqlParams) throws InvoiceLineDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InvoiceLineDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the invoice_line table that match the specified arbitrary SQL statement
	 */
	public InvoiceLine[] findByDynamicWhere(String sql, Object[] sqlParams) throws InvoiceLineDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new InvoiceLineDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
