-- MySQL Script generated by MySQL Workbench
-- Sun 12 Jun 2016 03:20:18 PM EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema fruits
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fruits` ;

-- -----------------------------------------------------
-- Schema fruits
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fruits` DEFAULT CHARACTER SET utf8 ;
USE `fruits` ;

-- -----------------------------------------------------
-- Table `fruits`.`business_partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`business_partner` ;

CREATE TABLE IF NOT EXISTS `fruits`.`business_partner` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `bp_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bp_phone` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bp_address` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `is_employee` BIT(1) NULL DEFAULT NULL COMMENT '',
  `is_customer` BIT(1) NULL DEFAULT NULL COMMENT '',
  `is_supplier` BIT(1) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`banks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`banks` ;

CREATE TABLE IF NOT EXISTS `fruits`.`banks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `bank_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `account_number` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `branch` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bp_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_banks_1_idx` (`bp_id` ASC)  COMMENT '',
  CONSTRAINT `fk_banks_1`
    FOREIGN KEY (`bp_id`)
    REFERENCES `fruits`.`business_partner` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`invoices` ;

CREATE TABLE IF NOT EXISTS `fruits`.`invoices` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NULL DEFAULT NULL COMMENT '',
  `grand_total` VARCHAR(45) NULL DEFAULT '0' COMMENT '',
  `bp_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `is_trx` BIT(1) NULL DEFAULT b'1' COMMENT 'true if sale\nfalse if purchase',
  `emp_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_sales_1_idx` (`bp_id` ASC)  COMMENT '',
  INDEX `fk_invoices_1_idx` (`emp_id` ASC)  COMMENT '',
  CONSTRAINT `fk_invoices_1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `fruits`.`business_partner` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sales_1`
    FOREIGN KEY (`bp_id`)
    REFERENCES `fruits`.`business_partner` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`stock` ;

CREATE TABLE IF NOT EXISTS `fruits`.`stock` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `stock_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`items` ;

CREATE TABLE IF NOT EXISTS `fruits`.`items` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quantity` DOUBLE NULL DEFAULT '0' COMMENT '',
  `stock_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `code` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `price` DOUBLE NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_items_1_idx` (`stock_id` ASC)  COMMENT '',
  CONSTRAINT `fk_items_1`
    FOREIGN KEY (`stock_id`)
    REFERENCES `fruits`.`stock` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`invoice_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`invoice_line` ;

CREATE TABLE IF NOT EXISTS `fruits`.`invoice_line` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `invoice_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `item_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `price` DOUBLE NULL DEFAULT '0' COMMENT '',
  `quantity` DOUBLE NULL DEFAULT '0' COMMENT '',
  `total_price` DOUBLE NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_invoice_line_1_idx` (`invoice_id` ASC)  COMMENT '',
  INDEX `fk_invoice_line_2_idx` (`item_id` ASC)  COMMENT '',
  CONSTRAINT `fk_invoice_line_1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `fruits`.`invoices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_invoice_line_2`
    FOREIGN KEY (`item_id`)
    REFERENCES `fruits`.`items` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`salary` ;

CREATE TABLE IF NOT EXISTS `fruits`.`salary` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATE NULL DEFAULT NULL COMMENT '',
  `bp_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `amount` DOUBLE NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_salary_1_idx` (`bp_id` ASC)  COMMENT '',
  CONSTRAINT `fk_salary_1`
    FOREIGN KEY (`bp_id`)
    REFERENCES `fruits`.`business_partner` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`tray`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`tray` ;

CREATE TABLE IF NOT EXISTS `fruits`.`tray` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `created_at` DATE NULL DEFAULT NULL COMMENT '',
  `bp_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `number_of_tray` INT(11) NULL DEFAULT NULL COMMENT '',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tray_1_idx` (`bp_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tray_1`
    FOREIGN KEY (`bp_id`)
    REFERENCES `fruits`.`business_partner` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fruits`.`tips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`tips` ;

CREATE TABLE IF NOT EXISTS `fruits`.`tips` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `bp_id` INT NULL COMMENT '',
  `amount_type` VARCHAR(45) NULL COMMENT '',
  `item_name` VARCHAR(45) NULL COMMENT '',
  `tips_type` VARCHAR(45) NULL COMMENT '',
  `worth` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_tips_1_idx` (`bp_id` ASC)  COMMENT '',
  CONSTRAINT `fk_tips_1`
    FOREIGN KEY (`bp_id`)
    REFERENCES `fruits`.`business_partner` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fruits`.`salaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fruits`.`salaries` ;

CREATE TABLE IF NOT EXISTS `fruits`.`salaries` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `bp_id` INT NULL COMMENT '',
  `amount` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_salaries_1_idx` (`bp_id` ASC)  COMMENT '',
  CONSTRAINT `fk_salaries_1`
    FOREIGN KEY (`bp_id`)
    REFERENCES `fruits`.`business_partner` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `fruits` ;

-- -----------------------------------------------------
-- Placeholder table for view `fruits`.`invoice_vw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fruits`.`invoice_vw` (`date` INT, `bp_id` INT, `is_trx` INT, `id` INT, `price` INT, `quantity` INT, `name` INT);

-- -----------------------------------------------------
-- Placeholder table for view `fruits`.`tray_vw`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fruits`.`tray_vw` (`created_at` INT, `number_of_tray` INT, `name` INT, `bp_name` INT);

-- -----------------------------------------------------
-- View `fruits`.`invoice_vw`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `fruits`.`invoice_vw` ;
DROP TABLE IF EXISTS `fruits`.`invoice_vw`;
USE `fruits`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fruits`.`invoice_vw` AS select `inv`.`date` AS `date`,`inv`.`bp_id` AS `bp_id`,`inv`.`is_trx` AS `is_trx`,`il`.`id` AS `id`,`il`.`price` AS `price`,`il`.`quantity` AS `quantity`,`i`.`name` AS `name` from ((`fruits`.`invoices` `inv` join `fruits`.`invoice_line` `il` on((`il`.`invoice_id` = `inv`.`id`))) join `fruits`.`items` `i` on((`i`.`id` = `il`.`item_id`)));

-- -----------------------------------------------------
-- View `fruits`.`tray_vw`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `fruits`.`tray_vw` ;
DROP TABLE IF EXISTS `fruits`.`tray_vw`;
USE `fruits`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `fruits`.`tray_vw` AS select `t`.`created_at` AS `created_at`,`t`.`number_of_tray` AS `number_of_tray`,`t`.`name` AS `name`,`b`.`bp_name` AS `bp_name` from (`fruits`.`tray` `t` join `fruits`.`business_partner` `b` on((`b`.`id` = `t`.`bp_id`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;