/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.exceptions;

public class InvoiceLineDaoException extends DaoException
{
	/**
	 * Method 'InvoiceLineDaoException'
	 * 
	 * @param message
	 */
	public InvoiceLineDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'InvoiceLineDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public InvoiceLineDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
