/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.factory;

import java.sql.Connection;
import com.app.dal.dao.*;
import com.app.dal.jdbc.*;

public class TipsDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return TipsDao
	 */
	public static TipsDao create()
	{
		return new TipsDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return TipsDao
	 */
	public static TipsDao create(Connection conn)
	{
		return new TipsDaoImpl( conn );
	}

}
