/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Banks implements Serializable
{
	/** 
	 * This attribute maps to the column id in the banks table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column bank_name in the banks table.
	 */
	protected String bankName;

	/** 
	 * This attribute maps to the column account_number in the banks table.
	 */
	protected String accountNumber;

	/** 
	 * This attribute maps to the column branch in the banks table.
	 */
	protected String branch;

	/** 
	 * This attribute maps to the column bp_id in the banks table.
	 */
	protected int bpId;

	/** 
	 * This attribute represents whether the primitive attribute bpId is null.
	 */
	protected boolean bpIdNull = true;

	/**
	 * Method 'Banks'
	 * 
	 */
	public Banks()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getBankName'
	 * 
	 * @return String
	 */
	public String getBankName()
	{
		return bankName;
	}

	/**
	 * Method 'setBankName'
	 * 
	 * @param bankName
	 */
	public void setBankName(String bankName)
	{
		this.bankName = bankName;
	}

	/**
	 * Method 'getAccountNumber'
	 * 
	 * @return String
	 */
	public String getAccountNumber()
	{
		return accountNumber;
	}

	/**
	 * Method 'setAccountNumber'
	 * 
	 * @param accountNumber
	 */
	public void setAccountNumber(String accountNumber)
	{
		this.accountNumber = accountNumber;
	}

	/**
	 * Method 'getBranch'
	 * 
	 * @return String
	 */
	public String getBranch()
	{
		return branch;
	}

	/**
	 * Method 'setBranch'
	 * 
	 * @param branch
	 */
	public void setBranch(String branch)
	{
		this.branch = branch;
	}

	/**
	 * Method 'getBpId'
	 * 
	 * @return int
	 */
	public int getBpId()
	{
		return bpId;
	}

	/**
	 * Method 'setBpId'
	 * 
	 * @param bpId
	 */
	public void setBpId(int bpId)
	{
		this.bpId = bpId;
		this.bpIdNull = false;
	}

	/**
	 * Method 'setBpIdNull'
	 * 
	 * @param value
	 */
	public void setBpIdNull(boolean value)
	{
		this.bpIdNull = value;
	}

	/**
	 * Method 'isBpIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBpIdNull()
	{
		return bpIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Banks)) {
			return false;
		}
		
		final Banks _cast = (Banks) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (bankName == null ? _cast.bankName != bankName : !bankName.equals( _cast.bankName )) {
			return false;
		}
		
		if (accountNumber == null ? _cast.accountNumber != accountNumber : !accountNumber.equals( _cast.accountNumber )) {
			return false;
		}
		
		if (branch == null ? _cast.branch != branch : !branch.equals( _cast.branch )) {
			return false;
		}
		
		if (bpId != _cast.bpId) {
			return false;
		}
		
		if (bpIdNull != _cast.bpIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (bankName != null) {
			_hashCode = 29 * _hashCode + bankName.hashCode();
		}
		
		if (accountNumber != null) {
			_hashCode = 29 * _hashCode + accountNumber.hashCode();
		}
		
		if (branch != null) {
			_hashCode = 29 * _hashCode + branch.hashCode();
		}
		
		_hashCode = 29 * _hashCode + bpId;
		_hashCode = 29 * _hashCode + (bpIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return BanksPk
	 */
	public BanksPk createPk()
	{
		return new BanksPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.Banks: " );
		ret.append( "id=" + id );
		ret.append( ", bankName=" + bankName );
		ret.append( ", accountNumber=" + accountNumber );
		ret.append( ", branch=" + branch );
		ret.append( ", bpId=" + bpId );
		return ret.toString();
	}

}
