/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class BusinessPartner implements Serializable
{
	/** 
	 * This attribute maps to the column id in the business_partner table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column bp_name in the business_partner table.
	 */
	protected String bpName;

	/** 
	 * This attribute maps to the column bp_phone in the business_partner table.
	 */
	protected String bpPhone;

	/** 
	 * This attribute maps to the column bp_address in the business_partner table.
	 */
	protected String bpAddress;

	/** 
	 * This attribute maps to the column is_employee in the business_partner table.
	 */
	protected short isEmployee;

	/** 
	 * This attribute represents whether the primitive attribute isEmployee is null.
	 */
	protected boolean isEmployeeNull = true;

	/** 
	 * This attribute maps to the column is_customer in the business_partner table.
	 */
	protected short isCustomer;

	/** 
	 * This attribute represents whether the primitive attribute isCustomer is null.
	 */
	protected boolean isCustomerNull = true;

	/** 
	 * This attribute maps to the column is_supplier in the business_partner table.
	 */
	protected short isSupplier;

	/** 
	 * This attribute represents whether the primitive attribute isSupplier is null.
	 */
	protected boolean isSupplierNull = true;

	/** 
	 * This attribute maps to the column balance in the business_partner table.
	 */
	protected double balance;

	/** 
	 * This attribute represents whether the primitive attribute balance is null.
	 */
	protected boolean balanceNull = true;

	/**
	 * Method 'BusinessPartner'
	 * 
	 */
	public BusinessPartner()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getBpName'
	 * 
	 * @return String
	 */
	public String getBpName()
	{
		return bpName;
	}

	/**
	 * Method 'setBpName'
	 * 
	 * @param bpName
	 */
	public void setBpName(String bpName)
	{
		this.bpName = bpName;
	}

	/**
	 * Method 'getBpPhone'
	 * 
	 * @return String
	 */
	public String getBpPhone()
	{
		return bpPhone;
	}

	/**
	 * Method 'setBpPhone'
	 * 
	 * @param bpPhone
	 */
	public void setBpPhone(String bpPhone)
	{
		this.bpPhone = bpPhone;
	}

	/**
	 * Method 'getBpAddress'
	 * 
	 * @return String
	 */
	public String getBpAddress()
	{
		return bpAddress;
	}

	/**
	 * Method 'setBpAddress'
	 * 
	 * @param bpAddress
	 */
	public void setBpAddress(String bpAddress)
	{
		this.bpAddress = bpAddress;
	}

	/**
	 * Method 'getIsEmployee'
	 * 
	 * @return short
	 */
	public short getIsEmployee()
	{
		return isEmployee;
	}

	/**
	 * Method 'setIsEmployee'
	 * 
	 * @param isEmployee
	 */
	public void setIsEmployee(short isEmployee)
	{
		this.isEmployee = isEmployee;
		this.isEmployeeNull = false;
	}

	/**
	 * Method 'setIsEmployeeNull'
	 * 
	 * @param value
	 */
	public void setIsEmployeeNull(boolean value)
	{
		this.isEmployeeNull = value;
	}

	/**
	 * Method 'isIsEmployeeNull'
	 * 
	 * @return boolean
	 */
	public boolean isIsEmployeeNull()
	{
		return isEmployeeNull;
	}

	/**
	 * Method 'getIsCustomer'
	 * 
	 * @return short
	 */
	public short getIsCustomer()
	{
		return isCustomer;
	}

	/**
	 * Method 'setIsCustomer'
	 * 
	 * @param isCustomer
	 */
	public void setIsCustomer(short isCustomer)
	{
		this.isCustomer = isCustomer;
		this.isCustomerNull = false;
	}

	/**
	 * Method 'setIsCustomerNull'
	 * 
	 * @param value
	 */
	public void setIsCustomerNull(boolean value)
	{
		this.isCustomerNull = value;
	}

	/**
	 * Method 'isIsCustomerNull'
	 * 
	 * @return boolean
	 */
	public boolean isIsCustomerNull()
	{
		return isCustomerNull;
	}

	/**
	 * Method 'getIsSupplier'
	 * 
	 * @return short
	 */
	public short getIsSupplier()
	{
		return isSupplier;
	}

	/**
	 * Method 'setIsSupplier'
	 * 
	 * @param isSupplier
	 */
	public void setIsSupplier(short isSupplier)
	{
		this.isSupplier = isSupplier;
		this.isSupplierNull = false;
	}

	/**
	 * Method 'setIsSupplierNull'
	 * 
	 * @param value
	 */
	public void setIsSupplierNull(boolean value)
	{
		this.isSupplierNull = value;
	}

	/**
	 * Method 'isIsSupplierNull'
	 * 
	 * @return boolean
	 */
	public boolean isIsSupplierNull()
	{
		return isSupplierNull;
	}

	/**
	 * Method 'getBalance'
	 * 
	 * @return double
	 */
	public double getBalance()
	{
		return balance;
	}

	/**
	 * Method 'setBalance'
	 * 
	 * @param balance
	 */
	public void setBalance(double balance)
	{
		this.balance = balance;
		this.balanceNull = false;
	}

	/**
	 * Method 'setBalanceNull'
	 * 
	 * @param value
	 */
	public void setBalanceNull(boolean value)
	{
		this.balanceNull = value;
	}

	/**
	 * Method 'isBalanceNull'
	 * 
	 * @return boolean
	 */
	public boolean isBalanceNull()
	{
		return balanceNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof BusinessPartner)) {
			return false;
		}
		
		final BusinessPartner _cast = (BusinessPartner) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (bpName == null ? _cast.bpName != bpName : !bpName.equals( _cast.bpName )) {
			return false;
		}
		
		if (bpPhone == null ? _cast.bpPhone != bpPhone : !bpPhone.equals( _cast.bpPhone )) {
			return false;
		}
		
		if (bpAddress == null ? _cast.bpAddress != bpAddress : !bpAddress.equals( _cast.bpAddress )) {
			return false;
		}
		
		if (isEmployee != _cast.isEmployee) {
			return false;
		}
		
		if (isEmployeeNull != _cast.isEmployeeNull) {
			return false;
		}
		
		if (isCustomer != _cast.isCustomer) {
			return false;
		}
		
		if (isCustomerNull != _cast.isCustomerNull) {
			return false;
		}
		
		if (isSupplier != _cast.isSupplier) {
			return false;
		}
		
		if (isSupplierNull != _cast.isSupplierNull) {
			return false;
		}
		
		if (balance != _cast.balance) {
			return false;
		}
		
		if (balanceNull != _cast.balanceNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (bpName != null) {
			_hashCode = 29 * _hashCode + bpName.hashCode();
		}
		
		if (bpPhone != null) {
			_hashCode = 29 * _hashCode + bpPhone.hashCode();
		}
		
		if (bpAddress != null) {
			_hashCode = 29 * _hashCode + bpAddress.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (int) isEmployee;
		_hashCode = 29 * _hashCode + (isEmployeeNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) isCustomer;
		_hashCode = 29 * _hashCode + (isCustomerNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) isSupplier;
		_hashCode = 29 * _hashCode + (isSupplierNull ? 1 : 0);
		long temp_balance = Double.doubleToLongBits(balance);
		_hashCode = 29 * _hashCode + (int) (temp_balance ^ (temp_balance >>> 32));
		_hashCode = 29 * _hashCode + (balanceNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return BusinessPartnerPk
	 */
	public BusinessPartnerPk createPk()
	{
		return new BusinessPartnerPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.BusinessPartner: " );
		ret.append( "id=" + id );
		ret.append( ", bpName=" + bpName );
		ret.append( ", bpPhone=" + bpPhone );
		ret.append( ", bpAddress=" + bpAddress );
		ret.append( ", isEmployee=" + isEmployee );
		ret.append( ", isCustomer=" + isCustomer );
		ret.append( ", isSupplier=" + isSupplier );
		ret.append( ", balance=" + balance );
		return ret.toString();
	}

}
