/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Invoices implements Serializable
{
	/** 
	 * This attribute maps to the column id in the invoices table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column date in the invoices table.
	 */
	protected Date date;

	/** 
	 * This attribute maps to the column grand_total in the invoices table.
	 */
	protected String grandTotal;

	/** 
	 * This attribute maps to the column bp_id in the invoices table.
	 */
	protected int bpId;

	/** 
	 * This attribute represents whether the primitive attribute bpId is null.
	 */
	protected boolean bpIdNull = true;

	/** 
	 * This attribute maps to the column is_trx in the invoices table.
	 */
	protected short isTrx;

	/** 
	 * This attribute represents whether the primitive attribute isTrx is null.
	 */
	protected boolean isTrxNull = true;

	/** 
	 * This attribute maps to the column emp_id in the invoices table.
	 */
	protected int empId;

	/** 
	 * This attribute represents whether the primitive attribute empId is null.
	 */
	protected boolean empIdNull = true;

	/**
	 * Method 'Invoices'
	 * 
	 */
	public Invoices()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getDate'
	 * 
	 * @return Date
	 */
	public Date getDate()
	{
		return date;
	}

	/**
	 * Method 'setDate'
	 * 
	 * @param date
	 */
	public void setDate(Date date)
	{
		this.date = date;
	}

	/**
	 * Method 'getGrandTotal'
	 * 
	 * @return String
	 */
	public String getGrandTotal()
	{
		return grandTotal;
	}

	/**
	 * Method 'setGrandTotal'
	 * 
	 * @param grandTotal
	 */
	public void setGrandTotal(String grandTotal)
	{
		this.grandTotal = grandTotal;
	}

	/**
	 * Method 'getBpId'
	 * 
	 * @return int
	 */
	public int getBpId()
	{
		return bpId;
	}

	/**
	 * Method 'setBpId'
	 * 
	 * @param bpId
	 */
	public void setBpId(int bpId)
	{
		this.bpId = bpId;
		this.bpIdNull = false;
	}

	/**
	 * Method 'setBpIdNull'
	 * 
	 * @param value
	 */
	public void setBpIdNull(boolean value)
	{
		this.bpIdNull = value;
	}

	/**
	 * Method 'isBpIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBpIdNull()
	{
		return bpIdNull;
	}

	/**
	 * Method 'getIsTrx'
	 * 
	 * @return short
	 */
	public short getIsTrx()
	{
		return isTrx;
	}

	/**
	 * Method 'setIsTrx'
	 * 
	 * @param isTrx
	 */
	public void setIsTrx(short isTrx)
	{
		this.isTrx = isTrx;
		this.isTrxNull = false;
	}

	/**
	 * Method 'setIsTrxNull'
	 * 
	 * @param value
	 */
	public void setIsTrxNull(boolean value)
	{
		this.isTrxNull = value;
	}

	/**
	 * Method 'isIsTrxNull'
	 * 
	 * @return boolean
	 */
	public boolean isIsTrxNull()
	{
		return isTrxNull;
	}

	/**
	 * Method 'getEmpId'
	 * 
	 * @return int
	 */
	public int getEmpId()
	{
		return empId;
	}

	/**
	 * Method 'setEmpId'
	 * 
	 * @param empId
	 */
	public void setEmpId(int empId)
	{
		this.empId = empId;
		this.empIdNull = false;
	}

	/**
	 * Method 'setEmpIdNull'
	 * 
	 * @param value
	 */
	public void setEmpIdNull(boolean value)
	{
		this.empIdNull = value;
	}

	/**
	 * Method 'isEmpIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isEmpIdNull()
	{
		return empIdNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Invoices)) {
			return false;
		}
		
		final Invoices _cast = (Invoices) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (date == null ? _cast.date != date : !date.equals( _cast.date )) {
			return false;
		}
		
		if (grandTotal == null ? _cast.grandTotal != grandTotal : !grandTotal.equals( _cast.grandTotal )) {
			return false;
		}
		
		if (bpId != _cast.bpId) {
			return false;
		}
		
		if (bpIdNull != _cast.bpIdNull) {
			return false;
		}
		
		if (isTrx != _cast.isTrx) {
			return false;
		}
		
		if (isTrxNull != _cast.isTrxNull) {
			return false;
		}
		
		if (empId != _cast.empId) {
			return false;
		}
		
		if (empIdNull != _cast.empIdNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (date != null) {
			_hashCode = 29 * _hashCode + date.hashCode();
		}
		
		if (grandTotal != null) {
			_hashCode = 29 * _hashCode + grandTotal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + bpId;
		_hashCode = 29 * _hashCode + (bpIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) isTrx;
		_hashCode = 29 * _hashCode + (isTrxNull ? 1 : 0);
		_hashCode = 29 * _hashCode + empId;
		_hashCode = 29 * _hashCode + (empIdNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InvoicesPk
	 */
	public InvoicesPk createPk()
	{
		return new InvoicesPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.Invoices: " );
		ret.append( "id=" + id );
		ret.append( ", date=" + date );
		ret.append( ", grandTotal=" + grandTotal );
		ret.append( ", bpId=" + bpId );
		ret.append( ", isTrx=" + isTrx );
		ret.append( ", empId=" + empId );
		return ret.toString();
	}

}
