/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class InvoiceVw implements Serializable
{
	/** 
	 * This attribute maps to the column date in the invoice_vw table.
	 */
	protected Date date;

	/** 
	 * This attribute maps to the column bp_id in the invoice_vw table.
	 */
	protected int bpId;

	/** 
	 * This attribute represents whether the primitive attribute bpId is null.
	 */
	protected boolean bpIdNull = true;

	/** 
	 * This attribute maps to the column is_trx in the invoice_vw table.
	 */
	protected short isTrx;

	/** 
	 * This attribute represents whether the primitive attribute isTrx is null.
	 */
	protected boolean isTrxNull = true;

	/** 
	 * This attribute maps to the column id in the invoice_vw table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column price in the invoice_vw table.
	 */
	protected double price;

	/** 
	 * This attribute represents whether the primitive attribute price is null.
	 */
	protected boolean priceNull = true;

	/** 
	 * This attribute maps to the column quantity in the invoice_vw table.
	 */
	protected double quantity;

	/** 
	 * This attribute represents whether the primitive attribute quantity is null.
	 */
	protected boolean quantityNull = true;

	/** 
	 * This attribute maps to the column name in the invoice_vw table.
	 */
	protected String name;

	/** 
	 * This attribute maps to the column invoice_id in the invoice_vw table.
	 */
	protected int invoiceId;

	/**
	 * Method 'InvoiceVw'
	 * 
	 */
	public InvoiceVw()
	{
	}

	/**
	 * Method 'getDate'
	 * 
	 * @return Date
	 */
	public Date getDate()
	{
		return date;
	}

	/**
	 * Method 'setDate'
	 * 
	 * @param date
	 */
	public void setDate(Date date)
	{
		this.date = date;
	}

	/**
	 * Method 'getBpId'
	 * 
	 * @return int
	 */
	public int getBpId()
	{
		return bpId;
	}

	/**
	 * Method 'setBpId'
	 * 
	 * @param bpId
	 */
	public void setBpId(int bpId)
	{
		this.bpId = bpId;
		this.bpIdNull = false;
	}

	/**
	 * Method 'setBpIdNull'
	 * 
	 * @param value
	 */
	public void setBpIdNull(boolean value)
	{
		this.bpIdNull = value;
	}

	/**
	 * Method 'isBpIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBpIdNull()
	{
		return bpIdNull;
	}

	/**
	 * Method 'getIsTrx'
	 * 
	 * @return short
	 */
	public short getIsTrx()
	{
		return isTrx;
	}

	/**
	 * Method 'setIsTrx'
	 * 
	 * @param isTrx
	 */
	public void setIsTrx(short isTrx)
	{
		this.isTrx = isTrx;
		this.isTrxNull = false;
	}

	/**
	 * Method 'setIsTrxNull'
	 * 
	 * @param value
	 */
	public void setIsTrxNull(boolean value)
	{
		this.isTrxNull = value;
	}

	/**
	 * Method 'isIsTrxNull'
	 * 
	 * @return boolean
	 */
	public boolean isIsTrxNull()
	{
		return isTrxNull;
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getPrice'
	 * 
	 * @return double
	 */
	public double getPrice()
	{
		return price;
	}

	/**
	 * Method 'setPrice'
	 * 
	 * @param price
	 */
	public void setPrice(double price)
	{
		this.price = price;
		this.priceNull = false;
	}

	/**
	 * Method 'setPriceNull'
	 * 
	 * @param value
	 */
	public void setPriceNull(boolean value)
	{
		this.priceNull = value;
	}

	/**
	 * Method 'isPriceNull'
	 * 
	 * @return boolean
	 */
	public boolean isPriceNull()
	{
		return priceNull;
	}

	/**
	 * Method 'getQuantity'
	 * 
	 * @return double
	 */
	public double getQuantity()
	{
		return quantity;
	}

	/**
	 * Method 'setQuantity'
	 * 
	 * @param quantity
	 */
	public void setQuantity(double quantity)
	{
		this.quantity = quantity;
		this.quantityNull = false;
	}

	/**
	 * Method 'setQuantityNull'
	 * 
	 * @param value
	 */
	public void setQuantityNull(boolean value)
	{
		this.quantityNull = value;
	}

	/**
	 * Method 'isQuantityNull'
	 * 
	 * @return boolean
	 */
	public boolean isQuantityNull()
	{
		return quantityNull;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'getInvoiceId'
	 * 
	 * @return int
	 */
	public int getInvoiceId()
	{
		return invoiceId;
	}

	/**
	 * Method 'setInvoiceId'
	 * 
	 * @param invoiceId
	 */
	public void setInvoiceId(int invoiceId)
	{
		this.invoiceId = invoiceId;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InvoiceVw)) {
			return false;
		}
		
		final InvoiceVw _cast = (InvoiceVw) _other;
		if (date == null ? _cast.date != date : !date.equals( _cast.date )) {
			return false;
		}
		
		if (bpId != _cast.bpId) {
			return false;
		}
		
		if (bpIdNull != _cast.bpIdNull) {
			return false;
		}
		
		if (isTrx != _cast.isTrx) {
			return false;
		}
		
		if (isTrxNull != _cast.isTrxNull) {
			return false;
		}
		
		if (id != _cast.id) {
			return false;
		}
		
		if (price != _cast.price) {
			return false;
		}
		
		if (priceNull != _cast.priceNull) {
			return false;
		}
		
		if (quantity != _cast.quantity) {
			return false;
		}
		
		if (quantityNull != _cast.quantityNull) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		if (invoiceId != _cast.invoiceId) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (date != null) {
			_hashCode = 29 * _hashCode + date.hashCode();
		}
		
		_hashCode = 29 * _hashCode + bpId;
		_hashCode = 29 * _hashCode + (bpIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + (int) isTrx;
		_hashCode = 29 * _hashCode + (isTrxNull ? 1 : 0);
		_hashCode = 29 * _hashCode + id;
		long temp_price = Double.doubleToLongBits(price);
		_hashCode = 29 * _hashCode + (int) (temp_price ^ (temp_price >>> 32));
		_hashCode = 29 * _hashCode + (priceNull ? 1 : 0);
		long temp_quantity = Double.doubleToLongBits(quantity);
		_hashCode = 29 * _hashCode + (int) (temp_quantity ^ (temp_quantity >>> 32));
		_hashCode = 29 * _hashCode + (quantityNull ? 1 : 0);
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		_hashCode = 29 * _hashCode + invoiceId;
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.InvoiceVw: " );
		ret.append( "date=" + date );
		ret.append( ", bpId=" + bpId );
		ret.append( ", isTrx=" + isTrx );
		ret.append( ", id=" + id );
		ret.append( ", price=" + price );
		ret.append( ", quantity=" + quantity );
		ret.append( ", name=" + name );
		ret.append( ", invoiceId=" + invoiceId );
		return ret.toString();
	}

}
