/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class InvoiceLine implements Serializable
{
	/** 
	 * This attribute maps to the column id in the invoice_line table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column invoice_id in the invoice_line table.
	 */
	protected int invoiceId;

	/** 
	 * This attribute represents whether the primitive attribute invoiceId is null.
	 */
	protected boolean invoiceIdNull = true;

	/** 
	 * This attribute maps to the column item_id in the invoice_line table.
	 */
	protected int itemId;

	/** 
	 * This attribute represents whether the primitive attribute itemId is null.
	 */
	protected boolean itemIdNull = true;

	/** 
	 * This attribute maps to the column price in the invoice_line table.
	 */
	protected double price;

	/** 
	 * This attribute represents whether the primitive attribute price is null.
	 */
	protected boolean priceNull = true;

	/** 
	 * This attribute maps to the column quantity in the invoice_line table.
	 */
	protected double quantity;

	/** 
	 * This attribute represents whether the primitive attribute quantity is null.
	 */
	protected boolean quantityNull = true;

	/** 
	 * This attribute maps to the column total_price in the invoice_line table.
	 */
	protected double totalPrice;

	/** 
	 * This attribute represents whether the primitive attribute totalPrice is null.
	 */
	protected boolean totalPriceNull = true;

	/**
	 * Method 'InvoiceLine'
	 * 
	 */
	public InvoiceLine()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getInvoiceId'
	 * 
	 * @return int
	 */
	public int getInvoiceId()
	{
		return invoiceId;
	}

	/**
	 * Method 'setInvoiceId'
	 * 
	 * @param invoiceId
	 */
	public void setInvoiceId(int invoiceId)
	{
		this.invoiceId = invoiceId;
		this.invoiceIdNull = false;
	}

	/**
	 * Method 'setInvoiceIdNull'
	 * 
	 * @param value
	 */
	public void setInvoiceIdNull(boolean value)
	{
		this.invoiceIdNull = value;
	}

	/**
	 * Method 'isInvoiceIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isInvoiceIdNull()
	{
		return invoiceIdNull;
	}

	/**
	 * Method 'getItemId'
	 * 
	 * @return int
	 */
	public int getItemId()
	{
		return itemId;
	}

	/**
	 * Method 'setItemId'
	 * 
	 * @param itemId
	 */
	public void setItemId(int itemId)
	{
		this.itemId = itemId;
		this.itemIdNull = false;
	}

	/**
	 * Method 'setItemIdNull'
	 * 
	 * @param value
	 */
	public void setItemIdNull(boolean value)
	{
		this.itemIdNull = value;
	}

	/**
	 * Method 'isItemIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isItemIdNull()
	{
		return itemIdNull;
	}

	/**
	 * Method 'getPrice'
	 * 
	 * @return double
	 */
	public double getPrice()
	{
		return price;
	}

	/**
	 * Method 'setPrice'
	 * 
	 * @param price
	 */
	public void setPrice(double price)
	{
		this.price = price;
		this.priceNull = false;
	}

	/**
	 * Method 'setPriceNull'
	 * 
	 * @param value
	 */
	public void setPriceNull(boolean value)
	{
		this.priceNull = value;
	}

	/**
	 * Method 'isPriceNull'
	 * 
	 * @return boolean
	 */
	public boolean isPriceNull()
	{
		return priceNull;
	}

	/**
	 * Method 'getQuantity'
	 * 
	 * @return double
	 */
	public double getQuantity()
	{
		return quantity;
	}

	/**
	 * Method 'setQuantity'
	 * 
	 * @param quantity
	 */
	public void setQuantity(double quantity)
	{
		this.quantity = quantity;
		this.quantityNull = false;
	}

	/**
	 * Method 'setQuantityNull'
	 * 
	 * @param value
	 */
	public void setQuantityNull(boolean value)
	{
		this.quantityNull = value;
	}

	/**
	 * Method 'isQuantityNull'
	 * 
	 * @return boolean
	 */
	public boolean isQuantityNull()
	{
		return quantityNull;
	}

	/**
	 * Method 'getTotalPrice'
	 * 
	 * @return double
	 */
	public double getTotalPrice()
	{
		return totalPrice;
	}

	/**
	 * Method 'setTotalPrice'
	 * 
	 * @param totalPrice
	 */
	public void setTotalPrice(double totalPrice)
	{
		this.totalPrice = totalPrice;
		this.totalPriceNull = false;
	}

	/**
	 * Method 'setTotalPriceNull'
	 * 
	 * @param value
	 */
	public void setTotalPriceNull(boolean value)
	{
		this.totalPriceNull = value;
	}

	/**
	 * Method 'isTotalPriceNull'
	 * 
	 * @return boolean
	 */
	public boolean isTotalPriceNull()
	{
		return totalPriceNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InvoiceLine)) {
			return false;
		}
		
		final InvoiceLine _cast = (InvoiceLine) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (invoiceId != _cast.invoiceId) {
			return false;
		}
		
		if (invoiceIdNull != _cast.invoiceIdNull) {
			return false;
		}
		
		if (itemId != _cast.itemId) {
			return false;
		}
		
		if (itemIdNull != _cast.itemIdNull) {
			return false;
		}
		
		if (price != _cast.price) {
			return false;
		}
		
		if (priceNull != _cast.priceNull) {
			return false;
		}
		
		if (quantity != _cast.quantity) {
			return false;
		}
		
		if (quantityNull != _cast.quantityNull) {
			return false;
		}
		
		if (totalPrice != _cast.totalPrice) {
			return false;
		}
		
		if (totalPriceNull != _cast.totalPriceNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		_hashCode = 29 * _hashCode + invoiceId;
		_hashCode = 29 * _hashCode + (invoiceIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + itemId;
		_hashCode = 29 * _hashCode + (itemIdNull ? 1 : 0);
		long temp_price = Double.doubleToLongBits(price);
		_hashCode = 29 * _hashCode + (int) (temp_price ^ (temp_price >>> 32));
		_hashCode = 29 * _hashCode + (priceNull ? 1 : 0);
		long temp_quantity = Double.doubleToLongBits(quantity);
		_hashCode = 29 * _hashCode + (int) (temp_quantity ^ (temp_quantity >>> 32));
		_hashCode = 29 * _hashCode + (quantityNull ? 1 : 0);
		long temp_totalPrice = Double.doubleToLongBits(totalPrice);
		_hashCode = 29 * _hashCode + (int) (temp_totalPrice ^ (temp_totalPrice >>> 32));
		_hashCode = 29 * _hashCode + (totalPriceNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return InvoiceLinePk
	 */
	public InvoiceLinePk createPk()
	{
		return new InvoiceLinePk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.InvoiceLine: " );
		ret.append( "id=" + id );
		ret.append( ", invoiceId=" + invoiceId );
		ret.append( ", itemId=" + itemId );
		ret.append( ", price=" + price );
		ret.append( ", quantity=" + quantity );
		ret.append( ", totalPrice=" + totalPrice );
		return ret.toString();
	}

}
