/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Loans implements Serializable
{
	/** 
	 * This attribute maps to the column bp_id in the loans table.
	 */
	protected int bpId;

	/** 
	 * This attribute represents whether the primitive attribute bpId is null.
	 */
	protected boolean bpIdNull = true;

	/** 
	 * This attribute maps to the column need_to_pay in the loans table.
	 */
	protected double needToPay;

	/** 
	 * This attribute represents whether the primitive attribute needToPay is null.
	 */
	protected boolean needToPayNull = true;

	/** 
	 * This attribute maps to the column pay_date in the loans table.
	 */
	protected Date payDate;

	/** 
	 * This attribute maps to the column paid in the loans table.
	 */
	protected double paid;

	/** 
	 * This attribute represents whether the primitive attribute paid is null.
	 */
	protected boolean paidNull = true;

	/** 
	 * This attribute maps to the column id in the loans table.
	 */
	protected int id;

	/**
	 * Method 'Loans'
	 * 
	 */
	public Loans()
	{
	}

	/**
	 * Method 'getBpId'
	 * 
	 * @return int
	 */
	public int getBpId()
	{
		return bpId;
	}

	/**
	 * Method 'setBpId'
	 * 
	 * @param bpId
	 */
	public void setBpId(int bpId)
	{
		this.bpId = bpId;
		this.bpIdNull = false;
	}

	/**
	 * Method 'setBpIdNull'
	 * 
	 * @param value
	 */
	public void setBpIdNull(boolean value)
	{
		this.bpIdNull = value;
	}

	/**
	 * Method 'isBpIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBpIdNull()
	{
		return bpIdNull;
	}

	/**
	 * Method 'getNeedToPay'
	 * 
	 * @return double
	 */
	public double getNeedToPay()
	{
		return needToPay;
	}

	/**
	 * Method 'setNeedToPay'
	 * 
	 * @param needToPay
	 */
	public void setNeedToPay(double needToPay)
	{
		this.needToPay = needToPay;
		this.needToPayNull = false;
	}

	/**
	 * Method 'setNeedToPayNull'
	 * 
	 * @param value
	 */
	public void setNeedToPayNull(boolean value)
	{
		this.needToPayNull = value;
	}

	/**
	 * Method 'isNeedToPayNull'
	 * 
	 * @return boolean
	 */
	public boolean isNeedToPayNull()
	{
		return needToPayNull;
	}

	/**
	 * Method 'getPayDate'
	 * 
	 * @return Date
	 */
	public Date getPayDate()
	{
		return payDate;
	}

	/**
	 * Method 'setPayDate'
	 * 
	 * @param payDate
	 */
	public void setPayDate(Date payDate)
	{
		this.payDate = payDate;
	}

	/**
	 * Method 'getPaid'
	 * 
	 * @return double
	 */
	public double getPaid()
	{
		return paid;
	}

	/**
	 * Method 'setPaid'
	 * 
	 * @param paid
	 */
	public void setPaid(double paid)
	{
		this.paid = paid;
		this.paidNull = false;
	}

	/**
	 * Method 'setPaidNull'
	 * 
	 * @param value
	 */
	public void setPaidNull(boolean value)
	{
		this.paidNull = value;
	}

	/**
	 * Method 'isPaidNull'
	 * 
	 * @return boolean
	 */
	public boolean isPaidNull()
	{
		return paidNull;
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Loans)) {
			return false;
		}
		
		final Loans _cast = (Loans) _other;
		if (bpId != _cast.bpId) {
			return false;
		}
		
		if (bpIdNull != _cast.bpIdNull) {
			return false;
		}
		
		if (needToPay != _cast.needToPay) {
			return false;
		}
		
		if (needToPayNull != _cast.needToPayNull) {
			return false;
		}
		
		if (payDate == null ? _cast.payDate != payDate : !payDate.equals( _cast.payDate )) {
			return false;
		}
		
		if (paid != _cast.paid) {
			return false;
		}
		
		if (paidNull != _cast.paidNull) {
			return false;
		}
		
		if (id != _cast.id) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + bpId;
		_hashCode = 29 * _hashCode + (bpIdNull ? 1 : 0);
		long temp_needToPay = Double.doubleToLongBits(needToPay);
		_hashCode = 29 * _hashCode + (int) (temp_needToPay ^ (temp_needToPay >>> 32));
		_hashCode = 29 * _hashCode + (needToPayNull ? 1 : 0);
		if (payDate != null) {
			_hashCode = 29 * _hashCode + payDate.hashCode();
		}
		
		long temp_paid = Double.doubleToLongBits(paid);
		_hashCode = 29 * _hashCode + (int) (temp_paid ^ (temp_paid >>> 32));
		_hashCode = 29 * _hashCode + (paidNull ? 1 : 0);
		_hashCode = 29 * _hashCode + id;
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return LoansPk
	 */
	public LoansPk createPk()
	{
		return new LoansPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.Loans: " );
		ret.append( "bpId=" + bpId );
		ret.append( ", needToPay=" + needToPay );
		ret.append( ", payDate=" + payDate );
		ret.append( ", paid=" + paid );
		ret.append( ", id=" + id );
		return ret.toString();
	}

}
