/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Patti implements Serializable
{
	/** 
	 * This attribute maps to the column id in the patti table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column patti_date in the patti table.
	 */
	protected Date pattiDate;

	/**
	 * Method 'Patti'
	 * 
	 */
	public Patti()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getPattiDate'
	 * 
	 * @return Date
	 */
	public Date getPattiDate()
	{
		return pattiDate;
	}

	/**
	 * Method 'setPattiDate'
	 * 
	 * @param pattiDate
	 */
	public void setPattiDate(Date pattiDate)
	{
		this.pattiDate = pattiDate;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Patti)) {
			return false;
		}
		
		final Patti _cast = (Patti) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (pattiDate == null ? _cast.pattiDate != pattiDate : !pattiDate.equals( _cast.pattiDate )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (pattiDate != null) {
			_hashCode = 29 * _hashCode + pattiDate.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return PattiPk
	 */
	public PattiPk createPk()
	{
		return new PattiPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.Patti: " );
		ret.append( "id=" + id );
		ret.append( ", pattiDate=" + pattiDate );
		return ret.toString();
	}

}
