/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Stock implements Serializable
{
	/** 
	 * This attribute maps to the column id in the stock table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column stock_name in the stock table.
	 */
	protected String stockName;

	/**
	 * Method 'Stock'
	 * 
	 */
	public Stock()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getStockName'
	 * 
	 * @return String
	 */
	public String getStockName()
	{
		return stockName;
	}

	/**
	 * Method 'setStockName'
	 * 
	 * @param stockName
	 */
	public void setStockName(String stockName)
	{
		this.stockName = stockName;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Stock)) {
			return false;
		}
		
		final Stock _cast = (Stock) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (stockName == null ? _cast.stockName != stockName : !stockName.equals( _cast.stockName )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (stockName != null) {
			_hashCode = 29 * _hashCode + stockName.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return StockPk
	 */
	public StockPk createPk()
	{
		return new StockPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.Stock: " );
		ret.append( "id=" + id );
		ret.append( ", stockName=" + stockName );
		return ret.toString();
	}

}
