/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.app.dal.dto;

import com.app.dal.dao.*;
import com.app.dal.factory.*;
import com.app.dal.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tray implements Serializable
{
	/** 
	 * This attribute maps to the column id in the tray table.
	 */
	protected int id;

	/** 
	 * This attribute maps to the column created_at in the tray table.
	 */
	protected Date createdAt;

	/** 
	 * This attribute maps to the column bp_id in the tray table.
	 */
	protected int bpId;

	/** 
	 * This attribute represents whether the primitive attribute bpId is null.
	 */
	protected boolean bpIdNull = true;

	/** 
	 * This attribute maps to the column number_of_tray in the tray table.
	 */
	protected int numberOfTray;

	/** 
	 * This attribute represents whether the primitive attribute numberOfTray is null.
	 */
	protected boolean numberOfTrayNull = true;

	/** 
	 * This attribute maps to the column name in the tray table.
	 */
	protected String name;

	/**
	 * Method 'Tray'
	 * 
	 */
	public Tray()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return int
	 */
	public int getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(int id)
	{
		this.id = id;
	}

	/**
	 * Method 'getCreatedAt'
	 * 
	 * @return Date
	 */
	public Date getCreatedAt()
	{
		return createdAt;
	}

	/**
	 * Method 'setCreatedAt'
	 * 
	 * @param createdAt
	 */
	public void setCreatedAt(Date createdAt)
	{
		this.createdAt = createdAt;
	}

	/**
	 * Method 'getBpId'
	 * 
	 * @return int
	 */
	public int getBpId()
	{
		return bpId;
	}

	/**
	 * Method 'setBpId'
	 * 
	 * @param bpId
	 */
	public void setBpId(int bpId)
	{
		this.bpId = bpId;
		this.bpIdNull = false;
	}

	/**
	 * Method 'setBpIdNull'
	 * 
	 * @param value
	 */
	public void setBpIdNull(boolean value)
	{
		this.bpIdNull = value;
	}

	/**
	 * Method 'isBpIdNull'
	 * 
	 * @return boolean
	 */
	public boolean isBpIdNull()
	{
		return bpIdNull;
	}

	/**
	 * Method 'getNumberOfTray'
	 * 
	 * @return int
	 */
	public int getNumberOfTray()
	{
		return numberOfTray;
	}

	/**
	 * Method 'setNumberOfTray'
	 * 
	 * @param numberOfTray
	 */
	public void setNumberOfTray(int numberOfTray)
	{
		this.numberOfTray = numberOfTray;
		this.numberOfTrayNull = false;
	}

	/**
	 * Method 'setNumberOfTrayNull'
	 * 
	 * @param value
	 */
	public void setNumberOfTrayNull(boolean value)
	{
		this.numberOfTrayNull = value;
	}

	/**
	 * Method 'isNumberOfTrayNull'
	 * 
	 * @return boolean
	 */
	public boolean isNumberOfTrayNull()
	{
		return numberOfTrayNull;
	}

	/**
	 * Method 'getName'
	 * 
	 * @return String
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Method 'setName'
	 * 
	 * @param name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tray)) {
			return false;
		}
		
		final Tray _cast = (Tray) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (createdAt == null ? _cast.createdAt != createdAt : !createdAt.equals( _cast.createdAt )) {
			return false;
		}
		
		if (bpId != _cast.bpId) {
			return false;
		}
		
		if (bpIdNull != _cast.bpIdNull) {
			return false;
		}
		
		if (numberOfTray != _cast.numberOfTray) {
			return false;
		}
		
		if (numberOfTrayNull != _cast.numberOfTrayNull) {
			return false;
		}
		
		if (name == null ? _cast.name != name : !name.equals( _cast.name )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id;
		if (createdAt != null) {
			_hashCode = 29 * _hashCode + createdAt.hashCode();
		}
		
		_hashCode = 29 * _hashCode + bpId;
		_hashCode = 29 * _hashCode + (bpIdNull ? 1 : 0);
		_hashCode = 29 * _hashCode + numberOfTray;
		_hashCode = 29 * _hashCode + (numberOfTrayNull ? 1 : 0);
		if (name != null) {
			_hashCode = 29 * _hashCode + name.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TrayPk
	 */
	public TrayPk createPk()
	{
		return new TrayPk(id);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.app.dal.dto.Tray: " );
		ret.append( "id=" + id );
		ret.append( ", createdAt=" + createdAt );
		ret.append( ", bpId=" + bpId );
		ret.append( ", numberOfTray=" + numberOfTray );
		ret.append( ", name=" + name );
		return ret.toString();
	}

}
